config/routes.rb
TestMyApp::Application.routes.draw do
  get "home/index"

   root :to => 'subjects#index'
   resources :subjects

   match ':controller(/:action(/:id(.:format)))'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :users
	has_and_belongs_to_many :categories
	has_many :comments
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/categories_articles.rb
class CategoriesArticles < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :articles
end

app/models/contact_number.rb
class ContactNumber < ActiveRecord::Base
	belongs_to :friends
end

app/models/friends.rb
class Friends < ActiveRecord::Base
	has_many :contact_number

	validates :name, :presence => true
	validates :address, :presence => true
	
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	validates :name, :presence => true
	validates :course, :presence => true
	has_one :subjecttopic
end

app/models/subjecttopic.rb
class Subjecttopic < ActiveRecord::Base
	belongs_to :subject
end

app/models/users.rb
class Users < ActiveRecord::Base
	has_many :articles, :order => 'published_at DESC, title ASC', :dependent => :nullify
	has_many :replies, :through => :articles, :source => :comments
end

app/controllers/book_controller.rb
class BookController < ApplicationController
	def index
	 @books = Book.all
	end	
	def new
		@book = Book.new
	end
	
	def create
		@book = Book.new(params[:post])
		if @post.save
			flash[:notice] = "post created"
			redirect_to book_path
		else
			render :new
		end
	end
	def edit
		@book = Book.find(params[:id])
	end
	def update
		@book = Book.find[params[:id])
		
		if @book.update_attributes(param[:post])
			flash[:notice] = "post updated"
			redirect_to book_path
		else
			flash[:notice] = "Ops, an error occured"
		end
	end
	def destroy
		@book = Book.find([params:id])
		if @book.destroy
			flash[:destroy] = "Book Deleted"
			redirect_to book_path
		else
			flash[:notice] = "ops an error occured"
			redirect_to book_path
		end
	end
	def show
		@book = Book.find(params[:id])
	end
end		

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	def index
		#@subjects = Subject.all
		@subjects = Subject.paginate :page => params[:page],:per_page=>2, :order => 'created_at DESC'
	end
	def new
		@subjects = Subject.new
	end
	def create
		@subjects = Subject.new(params[:subject])
		if @subjects.save
			redirect_to "/subjects" , flash[:message] => 'Subject Successfully added.'
		else
			render :action => 'new'
		end
	end
	def edit
		@subjects = Subject.find(params[:id])
	end
	def update
		@subjects = Subject.find(params[:id])
		@subjects.update_attributes(params[:subject])
		redirect_to "/subjects"
	end
	def show
		@subjects = Subject.find(params[:id])
	end
	def delete
		 Subject.delete(params[:id])
		redirect_to "/subjects"
		
	end
	
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
		render :text=> "Hello World"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/subjects/_form.html.erb
<h1>Subject Management</h1>
<%=form_for(@subjects) do |subject|%>
	<% if @subjects.errors.any? %>
		<% s = @subjects.errors.full_messages%>				
	<% else %>
			<li><%=flash[:message]%></li>
	<% end %>
	
	<table>
		<tr>
			<td><%=subject.label :Name%></td>
			<td><%=subject.text_field :name%></td><td>
				<%if !s.nil?%>
				<label style="Color:red"><%=s[0]%></label>
				<% end %>
			</td>
		</tr>
		
		<tr>
			<td><label>Course</label></td>
			<td><%=subject.text_field :course%></td><td><%if !s.nil?%>
				<label style="Color:red"><%=s[1]%></label>
				<% end %>
			</td>
		</tr>
		<tr>
			
			<td></td>
			<td><%= subject.submit %></td>
		</tr>
		
		
		
	</table>
<% end %>
	

app/views/subjects/edit.html.erb
<%=render 'form' %>
<%=link_to 'back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Subject Details</h1>
<table>
<%if @subjects %>
	<tr>
				<th>Name</th>
				<th>Course</th>
				<th>View</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			
	<% @subjects.each do |subject| %>
		
			<tr>
				<td><%=subject.name%></td>
				<td><%=subject.course%></td>
				<td><%= link_to 'view' , :controller => "subjects" , :action => 'show' , :id => subject.id%></td>
				<td><%= link_to 'edit' , :controller => "subjects" , :action => 'edit' , :id => subject.id%></td>
				<td><%= link_to 'delete',:controller => "subjects" , :action => 'delete' , :id => subject.id%></td>
				
			</tr>
			
	<% end %>
	<tr>
				<td><%=link_to 'New Item' ,:action => 'new'%></td>
			</tr>
	
	</table>
	<%=will_paginate @subjects%>
<% end %>

app/views/subjects/new.html.erb
<%= render 'form' %>

app/views/subjects/show.html.erb
<h1>Subject</h1>
<table>
	<tr>
		<td><strong>Subject :</strong></td>
		<td><%= @subjects.name %></td>
		
	</tr>
	<tr>
		<td><strong>Course :</strong></td>
		<td><%= @subjects.course %></td>

	</tr>
	<tr>
		<td><%= link_to 'back', :action => 'index' %></td>
	</tr>
</table>